repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.8
      args:
        - --line-length=99
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args:
        - "--max-line-length=99"
        - "--ignore=E501,E402,W503,E203"