import datetime as dt

beef_url = (
    "https://www.inac.uy/innovaportal/v/9799/10/innova.front/serie-semanal"
    "-ingreso-medio-de-exportacion---bovino-ovino-y-otros-productos")
pulp_url = (
    f"https://www.insee.fr/en/statistiques/serie/telecharger/010600339?ordre=antechronologique&"
    f"transposition=donneescolonne&periodeDebut=1&anneeDebut=1990&periodeFin=11&anneeFin="
    f"{dt.datetime.now().year}")
soybean_url = "https://www.quandl.com/api/v3/datasets/CHRIS/CME_S1.csv?api_key=3TPxACcrxy9WsE871Lqe"
what_url = "https://www.quandl.com/api/v3/datasets/CHRIS/CME_W1.csv?api_key=3TPxACcrxy9WsE871Lqe"
imf_url = "https://www.imf.org/~/media/Files/Research/CommodityPrices/Monthly/ExternalData.ashx"
milk1_url = "https://www.inale.org/estadisticas/"
milk2_url = "https://ec.europa.eu/info/sites/info/files/food-farming-fisheries/farming/documents/eu-milk-historical-price-series_en.xls"
cpi_url = "http://ine.gub.uy/c/document_library/get_file?uuid=2e92084a-94ec-4fec-b5ca-42b40d5d2826&groupId=10181"
cpi_product_url1 = "http://www.ine.gub.uy/c/document_library/get_file?uuid=668d4f77-74d8-46ba-8360-77bd867996df&groupId=10181"
cpi_product_url2 = "http://www.ine.gub.uy/c/document_library/get_file?uuid=39ef3b7a-8711-4222-af5a-722123fd799b&groupId=10181"
nxr_url = "http://ine.gub.uy/c/document_library/get_file?uuid=3fbf4ffd-a829-420c-aca9-9f01ecd7919a&groupId=10181"
nxr_daily_url = "https://www.bcu.gub.uy/_layouts/BCU.Cotizaciones/handler/FileHandler.ashx?op=downloadcotizacionesexcel&KeyValuePairs={%22KeyValuePairs%22:{%22Monedas%22:[{%22Val%22:%222224%22,%22Text%22:%22DLS.%20USA%20CABLE%22}],"
labor_url = "http://ine.gub.uy/c/document_library/get_file?uuid=50ae926c-1ddc-4409-afc6-1fecf641e3d0&groupId=10181"
wages1_url = "http://www.ine.gub.uy/c/document_library/get_file?uuid=a76433b7-5fba-40fc-9958-dd913338e989&groupId=10181"
wages2_url = "http://www.ine.gub.uy/c/document_library/get_file?uuid=97f07fd8-9410-476e-bf81-e6b1c11467ef&groupId=10181"
wap_url = "http://www.ine.gub.uy/c/document_library/get_file?uuid=2a5c1e6e-b02f-4a63-963f-925edea7c17e&groupId=10181"
fiscal_url = "https://www.gub.uy/ministerio-economia-finanzas/datos-y-estadisticas/datos"
reserves_url = "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Informe%20Diario%20Pasivos%20Monetarios/infd_"
reer_url = "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Paginas/Cambio-Real-Efectivo.aspx"
missing_reserves_url = "https://docs.google.com/spreadsheets/d/1tXwv8SaigbBrfBSSCVGBjSs88f3dgTq4nIANPn7vjYI/export?format=xlsx&authuser=0"
ar_cpi_url = "http://www.bcra.gov.ar/PublicacionesEstadisticas/Principales_variables_datos.asp"
ar_cpi_payload = f"fecha_desde=1970-01-01&fecha_hasta={dt.datetime.now().strftime('%Y-%m-%d')}&B1=Enviar&primeravez=1&fecha_desde=19600101&fecha_hasta={dt.datetime.now().strftime('%Y%m%d')}&serie=7931&serie1=0&serie2=0&serie3=0&serie4=0&detalle=Inflaci%F3n+mensual%A0%28variaci%F3n+en+%29"
trade_urls = {
    "x_prod_val": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/exp_ciiu_val.xls",
        "cols": "D:ZZZ", "currency": "USD", "unit": "Millones",
        "old_colnames": ['TOTAL EXPORTACIONES ', 'ACTIVIDADES PRIMARIAS',
                         'Agricultura, Ganadería, Caza y actividades de servicios conexas',
                         'Cultivos en general; horticultura; servicios agrícolas aplicados a estos cultivos',
                         'Cría de animales; caza ordinaria y servicios conexos; producción de pieles finas mediante actividades de caza ordinaria y con trampas; servicios ganaderos',
                         'Silvicultura, extracción de madera y actividades de servicios conexas',
                         'INDUSTRIAS MANUFACTURERAS',
                         'Elaboración de productos alimenticios y bebidas',
                         'Producción, procesamiento y conservación de carne y productos cárnicos',
                         'Elaboración y conservación de pescado y productos de pescado',
                         'Elaboración de productos lácteos',
                         'Elaboración de arroz y productos derivados del arroz',
                         'Elaboración de bebidas malteadas y de malta',
                         'Elaboración de productos alimenticios y bebidas - Resto ',
                         'Elaboración de Productos de Tabaco',
                         'Fabricación de productos textiles',
                         'Preparación, hilandería, tejeduría y acabado de productos textiles',
                         'Fabricación de prendas de vestir; adobo y  teñido de pieles',
                         'Curtido y adobo de cueros; fabricación de maletas, bolsos de mano, artículos de talabartería y guarnicionería, y calzado',
                         'Curtido y adobo de cueros; fabricación de maletas, bolsos de mano y artículos de talabartería y guarnicionería',
                         'Producción de madera y fabricación de productos de madera y corcho excepto muebles; fabricación de artículos de paja y de materiales trenzables',
                         'Fabricación de papel y de productos de papel; Actividades de edición e impresión y de reproducción de grabaciones',
                         'Fabricación de coque, productos de la refinación del petróleo y combustible nuclear',
                         'Fabricación de sustancias y productos químicos',
                         'Fabricación de sustancias químicas básicas, excepto abonos y compuestos de nitrógeno; fabricación de plásticos en formas primarias y de caucho sintético',
                         'Fabricación de abonos y compuestos de nitrógeno; Fabricación de plaguicidas y otros productos químicos de uso agropecuario',
                         'Fabricación de productos farmaceúticos, sustancias químicas medicinales y productos botánicos',
                         'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador',
                         'Fabricación de productos de caucho y plástico',
                         'Fabricación de metales comunes; Fabricación de otros productos minerales no metálicos',
                         'Fabricación de vehículos automotores, remolques y semirremolques; Fabricación de otros tipos de equipo de transporte',
                         'INDUSTRIAS MANUFACTURERAS - Resto',
                         'ELECTRICIDAD, GAS Y AGUA'],
        "new_colnames": ["Total exportaciones",
                         "Actividades primarias: total",
                         "Act. primarias: agricultura, ganadería y caza",
                         "Act. primarias: agricultura",
                         "Act. primarias: ganadería y caza",
                         "Act. primarias: silvicultura",
                         "Industrias manufactureras: total",
                         "Ind. manufacturera: alimentos y bebidas",
                         "Ind. manufacturera: alimentos y bebidas - carnes",
                         "Ind. manufacturera: alimentos y bebidas - pescado",
                         "Ind. manufacturera: alimentos y bebidas - lácteos",
                         "Ind. manufacturera: alimentos y bebidas - arroz",
                         "Ind. manufacturera: alimentos y bebidas - malta",
                         "Ind. manufacturera: alimentos y bebidas - otros",
                         "Ind. manufacturera: tabaco",
                         "Ind. manufacturera: textiles",
                         "Ind. manufacturera: textiles - hilandería y tejeduria",
                         "Ind. manufacturera: prendas de vestir",
                         "Ind. manufacturera: cueros",
                         "Ind. manufacturera: cueros - curtidos, adobos, derivados",
                         "Ind. manufacturera: madera",
                         "Ind. manufacturera: papel",
                         "Ind. manufacturera: refinación de petróleo",
                         "Ind. manufacturera: químicos",
                         "Ind. manufacturera: químicos - básicos excepto abonos",
                         "Ind. manufacturera: químicos - abonos",
                         "Ind. manufacturera: químicos - farmacéuticos",
                         "Ind. manufacturera: químicos - jabones y detergentes",
                         "Ind. manufacturera: caucho y plástico",
                         "Ind. manufacturera: metales y minerales no metálicos",
                         "Ind. manufacturera: automotores",
                         "Ind. manufacturera: otros",
                         "Electricidad, gas y agua: total"]},
    "x_prod_vol": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_exp_ciiu_ivf.xls",
        "cols": "D:ZZZ", "currency": "-", "unit": "2005=100",
        "old_colnames": ['TOTAL EXPORTACIONES ',
                         'AGRICULTURA, GANADERIA, CAZA Y SILVICULTURA',
                         'Trigo; servicios agrícolas aplicados al cultivo de trigo',
                         'Soja; girasol; servicios agrícolas aplicados al cultivo de soja y girasol',
                         'Productos de árboles frutales, uvas, y plantas cuyas hojas o frutas se utilizan para preparar bebidas o especias; servicios agrícolas aplicados a estos cultivos',
                         'Productos de la cría de ganado vacuno, ovino, caprino, caballar, excepto producción de leche, lana y cueros; servicios ganaderos aplicados a esta actividad',
                         'Madera y otros productos de la silvicultura. Servicios conexos',
                         'INDUSTRIAS MANUFACTURERAS',
                         'Carnes y productos del procesamiento y conservación de carne',
                         'Productos de la elaboración y conservación de pescado',
                         'Productos lácteos',
                         'Arroz elaborado y otros productos derivados del arroz',
                         'Productos de la elaboración de cacao, chocolate, productos de confitería y otros productos alimenticios n.c.p.\n',
                         'Bebidas malteadas y malta',
                         'Productos de lavaderos; hilados y tejidos; otros productos de la hilandería, tejeduría y acabado de productos textiles',
                         'Prendas de vestir; adobo y teñido de pieles',
                         'Cueros elaborados; artículos de talabartería y guarnicionería',
                         'Productos de aserrado y otros artículos de madera, excepto muebles',
                         'Papel, cartón y subproductos',
                         'Productos de la refinación del petróleo y combustible nuclear',
                         'Abonos y compuestos de nitrógeno',
                         'Sustancias químicas básicas, excepto abonos',
                         'Productos farmacéuticos, sustancias químicas medicinales y productos botánicos, de uso humano y animal',
                         'Productos de limpieza y tocador, primarias y de caucho sintético',
                         'Productos de caucho y plástico',
                         'Productos de fundición de hierro y acero; aluminio y otros metales no ferrosos',
                         'Vehículos automotores, remolques, semiremolques y contenedores; partes y piezas elaboradas para los mismos'],
        "new_colnames": ["Total exportaciones",
                         "Actividades primarias: total",
                         "Actividades primarias: trigo",
                         "Actividades primarias: soja y girasol",
                         "Actividades primarias: prod. árboles frutales",
                         "Actividades primarias: ganadería",
                         "Actividades primarias: silvicultura",
                         "Industrias manufactureras: total",
                         "Ind. manufacturera: alimentos y bebidas - carnes",
                         "Ind. manufacturera: alimentos y bebidas - pescado",
                         "Ind. manufacturera: alimentos y bebidas - lácteos",
                         "Ind. manufacturera: alimentos y bebidas - arroz",
                         "Ind. manufacturera: alimentos y bebidas - cacao",
                         "Ind. manufacturera: alimentos y bebidas - malta",
                         "Ind. manufacturera: textiles",
                         "Ind. manufacturera: prendas de vestir",
                         "Ind. manufacturera: cueros - curtidos, adobos, derivados",
                         "Ind. manufacturera: madera",
                         "Ind. manufacturera: papel",
                         "Ind. manufacturera: refinación de petróleo",
                         "Ind. manufacturera: químicos - abonos",
                         "Ind. manufacturera: químicos - básicos excepto abonos",
                         "Ind. manufacturera: químicos - farmacéuticos",
                         "Ind. manufacturera: químicos - jabones y detergentes",
                         "Ind. manufacturera: caucho y plástico",
                         "Ind. manufacturera: metales y minerales no metálicos",
                         "Ind. manufacturera: automotores"]},
    "x_prod_pri": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_exp_ciiu_ip.xls",
        "cols": "D:ZZZ", "currency": "USD", "unit": "2005=100",
        "old_colnames": ['TOTAL EXPORTACIONES ',
                         'AGRICULTURA, GANADERIA, CAZA Y SILVICULTURA',
                         'Trigo; servicios agrícolas aplicados al cultivo de trigo',
                         'Soja; girasol; servicios agrícolas aplicados al cultivo de soja y girasol',
                         'Productos de árboles frutales, uvas, y plantas cuyas hojas o frutas se utilizan para preparar bebidas o especias; servicios agrícolas aplicados a estos cultivos',
                         'Productos de la cría de ganado vacuno, ovino, caprino, caballar, excepto producción de leche, lana y cueros; servicios ganaderos aplicados a esta actividad',
                         'Madera y otros productos de la silvicultura. Servicios conexos',
                         'INDUSTRIAS MANUFACTURERAS',
                         'Carnes y productos del procesamiento y conservación de carne',
                         'Productos de la elaboración y conservación de pescado',
                         'Productos lácteos',
                         'Arroz elaborado y otros productos derivados del arroz',
                         'Productos de la elaboración de cacao, chocolate, productos de confitería y otros productos alimenticios n.c.p.',
                         'Bebidas malteadas y malta',
                         'Productos de lavaderos; hilados y tejidos; otros productos de la hilandería, tejeduría y acabado de productos textiles',
                         'Prendas de vestir; adobo y teñido de pieles',
                         'Cueros elaborados; artículos de talabartería y guarnicionería',
                         'Productos de aserrado y otros artículos de madera, excepto muebles',
                         'Papel, cartón y subproductos',
                         'Productos de la refinación del petróleo y combustible nuclear',
                         'Abonos y compuestos de nitrógeno',
                         'Sustancias químicas básicas, excepto abonos',
                         'Productos farmacéuticos, sustancias químicas medicinales y productos botánicos, de uso humano y animal',
                         'Productos de limpieza y tocador, primarias y de caucho sintético',
                         'Productos de caucho y plástico',
                         'Productos de fundición de hierro y acero; aluminio y otros metales no ferrosos',
                         'Vehículos automotores, remolques, semiremolques y contenedores; partes y piezas elaboradas para los mismos'],
        "new_colnames": ["Total exportaciones",
                         "Actividades primarias: total",
                         "Actividades primarias: trigo",
                         "Actividades primarias: soja y girasol",
                         "Actividades primarias: prod. árboles frutales",
                         "Actividades primarias: ganadería",
                         "Actividades primarias: silvicultura",
                         "Industrias manufactureras: total",
                         "Ind. manufacturera: alimentos y bebidas - carnes",
                         "Ind. manufacturera: alimentos y bebidas - pescado",
                         "Ind. manufacturera: alimentos y bebidas - lácteos",
                         "Ind. manufacturera: alimentos y bebidas - arroz",
                         "Ind. manufacturera: alimentos y bebidas - cacao",
                         "Ind. manufacturera: alimentos y bebidas - malta",
                         "Ind. manufacturera: textiles",
                         "Ind. manufacturera: prendas de vestir",
                         "Ind. manufacturera: cueros - curtidos, adobos, derivados",
                         "Ind. manufacturera: madera",
                         "Ind. manufacturera: papel",
                         "Ind. manufacturera: refinación de petróleo",
                         "Ind. manufacturera: químicos - abonos",
                         "Ind. manufacturera: químicos - básicos excepto abonos",
                         "Ind. manufacturera: químicos - farmacéuticos",
                         "Ind. manufacturera: químicos - jabones y detergentes",
                         "Ind. manufacturera: caucho y plástico",
                         "Ind. manufacturera: metales y minerales no metálicos",
                         "Ind. manufacturera: automotores"]},
    "x_dest_val": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/exp_pais_val.xls",
        "cols": "B:ZZZ", "currency": "USD", "unit": "Millones",
        "old_colnames": ['TOTAL EXPORTACIONES', 'AMERICA', 'ALADI 2/',
                         'Argentina', 'Brasil', 'Paraguay',
                         'Sub-total MERCOSUR (4 PAISES)', 'Venezuela',
                         'Sub-total MERCOSUR (5 PAISES)', 'Bolivia', 'Chile',
                         'México', 'Otros de Aladi', 'CANADA',
                         'ESTADOS UNIDOS', 'RESTO DE AMERICA', 'EUROPA',
                         'U.E. (UNION EUROPEA)', 'Alemania', 'España',
                         'Francia', 'Italia', 'Países Bajos', 'Reino Unido',
                         'Otros de la U.E.', 'AELC (EFTA)1/',
                         'RESTO DE EUROPA', 'Rusia', 'RESTO DEL MUNDO',
                         'AFRICA', 'ASIA (excl. M. Oriente)',
                         'China (Continental)', 'Corea del Sur', 'Taiwán',
                         'Hong Kong', 'Japón', 'Otros de Asia',
                         'MEDIO ORIENTE', 'Arabia', 'Irán', 'Israel',
                         'Otros del Medio Oriente', 'OTROS PAISES'],
        "new_colnames": ["Total exportaciones",
                         "América: total",
                         "América: ALADI",
                         "América: Argentina",
                         "América: Brasil",
                         "América: Paraguay",
                         "América: MERCOSUR 4 países",
                         "América: Venezuela",
                         "América: MERCOSUR 5 países",
                         "América: Bolivia",
                         "América: Chile",
                         "América: México",
                         "América: otros ALADI",
                         "América: Canadá",
                         "América: Estados Unidos",
                         "América: otros",
                         "Europa: total",
                         "Europa: Unión Europea - total",
                         "Europa: UE - Alemania",
                         "Europa: UE - España",
                         "Europa: UE - Francia",
                         "Europa: UE - Italia",
                         "Europa: UE - Países Bajos",
                         "Europa: UE - Reino Unido",
                         "Europa: UE - otros",
                         "Europa: EFTA",
                         "Europa: otros",
                         "Europa: otros - Rusia",
                         "Resto del mundo: total",
                         "Resto del mundo: África",
                         "Resto del mundo: Asia - total",
                         "Resto del mundo: Asia - China",
                         "Resto del mundo: Asia - Corea del Sur",
                         "Resto del mundo: Asia - Taiwán",
                         "Resto del mundo: Asia - Hong Kong",
                         "Resto del mundo: Asia - Japón",
                         "Resto del mundo: Asia - otros",
                         "Resto del mundo: Medio Oriente - total",
                         "Resto del mundo: Medio Oriente - Arabia",
                         "Resto del mundo: Medio Oriente - Irán",
                         "Resto del mundo: Medio Oriente - Israel",
                         "Resto del mundo: Medio Oriente - otros",
                         "Resto del mundo: otros"]},
    "x_dest_vol": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_exp_pais_ivf.xls",
        "cols": "B:ZZZ", "currency": "-", "unit": "2005=100",
        "old_colnames": ['TOTAL EXPORTACIONES', 'AMERICA', 'ALADI 1/',
                         'Argentina', 'Brasil', 'Paraguay',
                         'SUB-TOTAL  MERCOSUR (4 PAISES)', 'Venezuela',
                         'SUB-TOTAL  MERCOSUR (5 PAISES)', 'Chile', 'México',
                         'CANADA', 'ESTADOS UNIDOS', 'EUROPA',
                         'U.E. (UNION EUROPEA)', 'Alemania', 'España',
                         'Francia', 'Italia', 'Países Bajos', 'Reino Unido',
                         'RESTO DE EUROPA', 'Rusia', 'RESTO DEL MUNDO'],
        "new_colnames": ["Total exportaciones",
                         "América: total",
                         "América: ALADI",
                         "América: Argentina",
                         "América: Brasil",
                         "América: Paraguay",
                         "América: MERCOSUR 4 países",
                         "América: Venezuela",
                         "América: MERCOSUR 5 países",
                         "América: Chile",
                         "América: México",
                         "América: Canadá",
                         "América: Estados Unidos",
                         "Europa: total",
                         "Europa: Unión Europea - total",
                         "Europa: UE - Alemania",
                         "Europa: UE - España",
                         "Europa: UE - Francia",
                         "Europa: UE - Italia",
                         "Europa: UE - Países Bajos",
                         "Europa: UE - Reino Unido",
                         "Europa: otros",
                         "Europa: otros - Rusia",
                         "Resto del mundo: total"]},
    "x_dest_pri": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_exp_pais_ip.xls",
        "cols": "B:ZZZ", "currency": "USD", "unit": "2005=100",
        "old_colnames": ['TOTAL EXPORTACIONES', 'AMERICA', 'ALADI 1/',
                         'Argentina', 'Brasil', 'Paraguay',
                         'Sub-total MERCOSUR (4 PAISES)', 'Venezuela',
                         'SUB-TOTAL  MERCOSUR (5 PAISES)', 'Chile', 'México',
                         'CANADA', 'ESTADOS UNIDOS', 'EUROPA',
                         'U.E. (UNION EUROPEA)', 'Alemania', 'España',
                         'Francia', 'Italia', 'Países Bajos', 'Reino Unido',
                         'RESTO DE EUROPA', 'Rusia', 'RESTO DEL MUNDO'],
        "new_colnames": ["Total exportaciones",
                         "América: total",
                         "América: ALADI",
                         "América: Argentina",
                         "América: Brasil",
                         "América: Paraguay",
                         "América: MERCOSUR 4 países",
                         "América: Venezuela",
                         "América: MERCOSUR 5 países",
                         "América: Chile",
                         "América: México",
                         "América: Canadá",
                         "América: Estados Unidos",
                         "Europa: total",
                         "Europa: Unión Europea - total",
                         "Europa: UE - Alemania",
                         "Europa: UE - España",
                         "Europa: UE - Francia",
                         "Europa: UE - Italia",
                         "Europa: UE - Países Bajos",
                         "Europa: UE - Reino Unido",
                         "Europa: otros",
                         "Europa: otros - Rusia",
                         "Resto del mundo: total"]},
    "m_sect_val": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/imp_gce_val.xls",
        "cols": "C:ZZZ", "currency": "USD", "unit": "Millones",
        "old_colnames": ['TOTAL IMPORTACIONES FOB ',
                         'TOTAL IMPORTACIONES CIF ',
                         'TOTAL IMPORTACIONES CIF SIN PETRÓLEO, DESTILADOS Y ENERGÍA ELÉCTRICA',
                         'CONSUMO', 'Alimentos y bebidas',
                         'Automotores y otros de transporte', 'Duraderos',
                         'Otros de consumo', 'CAPITAL', 'Maquinaria y equipos',
                         'Público', 'Privado', 'Equipos de transporte',
                         'Público', 'Privado', 'INTERMEDIOS ',
                         'Petróleo y destilados ', 'Energía eléctrica',
                         'Intermedios sin petróleo, destilados y energía eléctrica',
                         'Alimentos y bebidas',
                         'Piezas y accesorios de transporte',
                         'Otros insumos intermedios',
                         'Suministros industriales básicos',
                         'Suministros industriales elaborados', 'Resto'],
        "new_colnames": ["Total importaciones: FOB",
                         "Total importaciones: CIF ",
                         "Total importaciones: CIF sin petróleo y energía eléct.",
                         "Consumo: total",
                         "Consumo: alimentos y bebidas",
                         "Consumo: automotores",
                         "Consumo: duraderos",
                         "Consumo: otros",
                         "Capital: total",
                         "Capital: maquinaria y equipos",
                         "Capital: maquinaria y equipos - público",
                         "Capital: maquinaria y equipos - privado",
                         "Capital: equipos de transporte",
                         "Capital: equipos de transporte - público",
                         "Capital: equipos de transporte - privado",
                         "Intermedios: total",
                         "Intermedios: petróleo y destilados",
                         "Intermedios: energía eléctrica",
                         "Intermedios: total sin petróleo y energía eléctrica",
                         "Intermedios: alimentos y bebidas",
                         "Intermedios: piezas de transporte",
                         "Intermedios: otros",
                         "Intermedios: otros - industriales básicos",
                         "Intermedios: otros - industriales elaborados",
                         "Intermedios: otros - resto"]},
    "m_sect_vol": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_imp_gce_ivf.xls",
        "cols": "B:ZZZ", "currency": "-", "unit": "2005=100",
        "old_colnames": ['TOTAL IMPORTACIONES', 'CONSUMO',
                         'ALIMENTOS Y BEBIDAS PARA LOS HOGARES',
                         'AUTOMOTORES Y OTROS DE TRANSPORTE',
                         'CONSUMO DURADERO', 'OTROS DE CONSUMO', 'CAPITAL',
                         'INTERMEDIOS', 'PETROLEO Y DESTILADOS',
                         'INTERMEDIOS SIN PETROLEO, DESTILADOS Y ENERGIA ELECTRICA',
                         'ALIMENTOS Y BEBIDAS PARA LA INDUSTRIA',
                         'PIEZAS Y ACCESORIOS DE TRANSPORTE',
                         'OTROS INSUMOS INTERMEDIOS'],
        "new_colnames": ["Total importaciones",
                         "Consumo: total",
                         "Consumo: alimentos y bebidas",
                         "Consumo: automotores",
                         "Consumo: duraderos",
                         "Consumo: otros",
                         "Capital: total",
                         "Intermedios: total",
                         "Intermedios: petróleo",
                         "Intermedios: total sin petróleo y energía eléctrica",
                         "Intermedios: alimentos y bebidas",
                         "Intermedios: transporte",
                         "Intermedios: otros"]},
    "m_sect_pri": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_imp_gce_ip.xls",
        "cols": "B:ZZZ", "currency": "USD", "unit": "2005=100",
        "old_colnames": ['TOTAL IMPORTACIONES', 'CONSUMO',
                         'ALIMENTOS Y BEBIDAS PARA LOS HOGARES',
                         'AUTOMOTORES Y OTROS DE TRANSPORTE',
                         'CONSUMO DURADERO', 'OTROS DE CONSUMO', 'CAPITAL',
                         'INTERMEDIOS', 'PETROLEO Y DESTILADOS',
                         'INTERMEDIOS SIN PETROLEO, DESTILADOS Y ENERGIA ELECTRICA',
                         'ALIMENTOS Y BEBIDAS PARA LA INDUSTRIA',
                         'PIEZAS Y ACCESORIOS DE TRANSPORTE',
                         'OTROS INSUMOS INTERMEDIOS'],
        "new_colnames": ["Total importaciones",
                         "Consumo: total",
                         "Consumo: alimentos y bebidas",
                         "Consumo: automotores",
                         "Consumo: duraderos",
                         "Consumo: otros",
                         "Capital: total",
                         "Intermedios: total",
                         "Intermedios: petróleo",
                         "Intermedios: total sin petróleo y energía eléctrica",
                         "Intermedios: alimentos y bebidas",
                         "Intermedios: transporte",
                         "Intermedios: otros"]},
    "m_orig_val": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/imp_pais_val.xls",
        "cols": "B:ZZZ", "currency": "USD", "unit": "Millones",
        "old_colnames": ['TOTAL IMPORTACIONES CIF ', 'AMERICA', 'ALADI 2/',
                         'Argentina', 'Brasil', 'Paraguay',
                         'Sub-total MERCOSUR (4 PAISES)', 'Venezuela',
                         'Sub-total MERCOSUR (5 PAISES)', 'Bolivia', 'Chile',
                         'México', 'Otros de Aladi', 'CANADA',
                         'ESTADOS UNIDOS', 'RESTO DE AMERICA', 'EUROPA',
                         'U.E. (UNION EUROPEA)', 'Alemania', 'España',
                         'Francia', 'Italia', 'Países Bajos', 'Reino Unido',
                         'Otros de la U.E.', 'AELC (EFTA)1/',
                         'RESTO DE EUROPA', 'Rusia', 'RESTO DEL MUNDO',
                         'AFRICA', 'ASIA (excl. M. Oriente)',
                         'China (Continental)', 'Corea del Sur', 'Taiwán',
                         'Hong Kong', 'Japón', 'Otros de Asia',
                         'MEDIO ORIENTE', 'Arabia', 'Irán', 'Israel',
                         'Otros del Medio Oriente', 'OTROS PAISES'],
        "new_colnames": ["Total importaciones",
                         "América: total",
                         "América: ALADI",
                         "América: Argentina",
                         "América: Brasil",
                         "América: Paraguay",
                         "América: MERCOSUR 4 países",
                         "América: Venezuela",
                         "América: MERCOSUR 5 países",
                         "América: Bolivia",
                         "América: Chile",
                         "América: México",
                         "América: otros ALADI",
                         "América: Canadá",
                         "América: Estados Unidos",
                         "América: otros",
                         "Europa: total",
                         "Europa: Unión Europea - total",
                         "Europa: UE - Alemania",
                         "Europa: UE - España",
                         "Europa: UE - Francia",
                         "Europa: UE - Italia",
                         "Europa: UE - Países Bajos",
                         "Europa: UE - Reino Unido",
                         "Europa: UE - otros",
                         "Europa: EFTA",
                         "Europa: otros",
                         "Europa: otros - Rusia",
                         "Resto del mundo: total",
                         "Resto del mundo: África",
                         "Resto del mundo: Asia - total",
                         "Resto del mundo: Asia - China",
                         "Resto del mundo: Asia - Corea del Sur",
                         "Resto del mundo: Asia - Taiwán",
                         "Resto del mundo: Asia - Hong Kong",
                         "Resto del mundo: Asia - Japón",
                         "Resto del mundo: Asia - otros",
                         "Resto del mundo: Medio Oriente - total",
                         "Resto del mundo: Medio Oriente - Arabia",
                         "Resto del mundo: Medio Oriente - Irán",
                         "Resto del mundo: Medio Oriente - Israel",
                         "Resto del mundo: Medio Oriente - otros",
                         "Resto del mundo: otros"]},
    "m_orig_vol": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_imp_pais_ivf.xls",
        "cols": "B:ZZZ", "currency": "-", "unit": "2005=100",
        "old_colnames": ['TOTAL IMPORTACIONES', 'AMERICA', 'ALADI 1/',
                         'Argentina', 'Brasil', 'Paraguay',
                         'Sub-total MERCOSUR (4 PAISES)', 'Venezuela',
                         'SUB-TOTAL  MERCOSUR (5 PAISES)', 'Chile', 'México',
                         'CANADA', 'ESTADOS UNIDOS', 'EUROPA',
                         'U.E. (UNION EUROPEA)', 'Alemania', 'España',
                         'Francia', 'Italia', 'Países Bajos', 'Reino Unido',
                         'RUSIA', 'RESTO DEL MUNDO', 'China (Continental)'],
        "new_colnames": ["Total importaciones",
                         "América: total",
                         "América: ALADI",
                         "América: Argentina",
                         "América: Brasil",
                         "América: Paraguay",
                         "América: MERCOSUR 4 países",
                         "América: Venezuela",
                         "América: MERCOSUR 5 países",
                         "América: Chile",
                         "América: México",
                         "América: Canadá",
                         "América: Estados Unidos",
                         "Europa: total",
                         "Europa: Unión Europea - total",
                         "Europa: UE - Alemania",
                         "Europa: UE - España",
                         "Europa: UE - Francia",
                         "Europa: UE - Italia",
                         "Europa: UE - Países Bajos",
                         "Europa: UE - Reino Unido",
                         "Europa: Rusia",
                         "Resto del mundo: total",
                         "Resto del mundo: China"]},
    "m_orig_pri": {
        "url": "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/ComercioExterior_ICB/web_imp_pais_ip.xls",
        "cols": "B:ZZZ", "currency": "USD", "unit": "2005=100",
        "old_colnames": ['TOTAL IMPORTACIONES', 'AMERICA', 'ALADI 1/',
                         'Argentina', 'Brasil', 'Paraguay',
                         'Sub-total MERCOSUR (4 PAISES)', 'Venezuela',
                         'SUB-TOTAL  MERCOSUR (5 PAISES)', 'Chile', 'México',
                         'CANADA', 'ESTADOS UNIDOS', 'EUROPA',
                         'U.E. (UNION EUROPEA)', 'Alemania', 'España',
                         'Francia', 'Italia', 'Países Bajos', 'Reino Unido',
                         'RUSIA', 'RESTO DEL MUNDO', 'China (Continental)'],
        "new_colnames": ["Total importaciones",
                         "América: total",
                         "América: ALADI",
                         "América: Argentina",
                         "América: Brasil",
                         "América: Paraguay",
                         "América: MERCOSUR 4 países",
                         "América: Venezuela",
                         "América: MERCOSUR 5 países",
                         "América: Chile",
                         "América: México",
                         "América: Canadá",
                         "América: Estados Unidos",
                         "Europa: total",
                         "Europa: Unión Europea - total",
                         "Europa: UE - Alemania",
                         "Europa: UE - España",
                         "Europa: UE - Francia",
                         "Europa: UE - Italia",
                         "Europa: UE - Países Bajos",
                         "Europa: UE - Reino Unido",
                         "Europa: Rusia",
                         "Resto del mundo: total",
                         "Resto del mundo: China"]}
}

fiscal_sheets = {
    "Sector Público No Financiero":
        {"Name": "nfps",
         "Colnames": ["Ingresos: SPNF",
                      "Ingresos: Gobierno central",
                      "Ingresos: DGI", "Ingresos: IRP",
                      "Ingresos: Comercio ext.",
                      "Ingresos: Otros", "Ingresos: BPS",
                      "Ingresos: Res. primario corriente EEPP",
                      "Egresos: Primarios SPNF",
                      "Egresos: Primarios corrientes GC-BPS",
                      "Egresos: Remuneraciones",
                      "Egresos: No personales",
                      "Egresos: Pasividades",
                      "Egresos: Transferencias",
                      "Egresos: Inversiones",
                      "Resultado: Primario intendencias",
                      "Resultado: Primario BSE",
                      "Resultado: Primario SPNF",
                      "Intereses: Totales", "Intereses: GC-BPS",
                      "Intereses: EEPP",
                      "Intereses: Intendencias",
                      "Intereses: BSE",
                      "Resultado: Global SPNF"]},
    "Sector Público Consolidado":
        {"Name": "gps",
         "Colnames": ["Resultado: Primario SPNF",
                      "Intereses: SPNF", "Resultado: Global SPNF",
                      "Resultado: Primario BCU", "Intereses: BCU",
                      "Resultado: Global BCU",
                      "Resultado: Primario SPC",
                      "Resultado: Global SPC"]},
    "Gobierno Central - BPS":
        {"Name": "gc-bps",
         "Colnames": ["Ingresos: GC-BPS", "Ingresos: GC",
                      "Ingresos: Comercio ext.", "Ingresos: DGI",
                      "Ingresos: DGI bruto", "Ingresos: DGI CDI",
                      "Ingresos: Loterías",
                      "Ingresos: Venta energía",
                      "Ingresos: TGN/otros", "Ingresos: FIMTOP",
                      "Ingresos: Aportes EEPP", "Ingresos: IRP",
                      "Ingresos: Rec. Lib. Disp",
                      "Ingresos: BPS neto", "Ingresos: BPS bruto",
                      "Ingresos: FSS",
                      "Ingresos: BPS CDI", "Ingresos: BPS otros",
                      "Egresos: GC-BPS",
                      "Egresos: Remuneraciones",
                      "Egresos: Remuneraciones adm. central",
                      "Egresos: Remuneraciones org. docentes",
                      "Egresos: Remuneraciones retenc./otros",
                      "Egresos: Remuneraciones BPS",
                      "Egresos: Pasividades",
                      "Egresos: Pasividades Caja Policial",
                      "Egresos: Pasividades Caja Militar",
                      "Egresos: Pasividades BPS",
                      "Egresos: No personales",
                      "Egresos: No personales adm. central",
                      "Egresos: No personales org. docentes",
                      "Egresos: No personales suministros",
                      "Egresos: No personales plan emergencia",
                      "Egresos: No personales BPS",
                      "Egresos: Transferencias",
                      "Egresos: Transferencias GC",
                      "Egresos: Transferencias GC Entes",
                      "Egresos: Transferencias GC deuda",
                      "Egresos: Transferencias GC otros org.",
                      "Egresos: Transferencias GC rentas afectadas",
                      "Egresos: Transferencias BPS",
                      "Egresos: Transferencias BPS enfermedad",
                      "Egresos: Transferencias BPS AFAM y otras prestaciones",
                      "Egresos: Transferencias BPS desempleo",
                      "Egresos: Transferencias BPS 2",
                      "Egresos: Transferencias BPS -IRP/IRPF",
                      "Egresos: Transferencias BPS AFAP",
                      "Egresos: Transferencias BPS otros",
                      "Egresos: Transferencias otros",
                      "Egresos: Inversión",
                      "Egresos: Inversión MTOP",
                      "Egresos: Inversión MVOTMA",
                      "Egresos: Inversión Presidencia",
                      "Egresos: Inversión org. docentes",
                      "Egresos: Inversión resto",
                      "Intereses: Total", "Intereses: GC",
                      "Intereses: BPS-FSS",
                      "Resultado: Global GC-BPS"]},
    "Empresas Públicas Consolidado":
        {"Name": "pe",
         "Colnames": ["Ingresos",
                      "Ingresos: Venta bienes y servicios",
                      "Ingresos: Otros",
                      "Ingresos: Transferencias GC", "Egresos",
                      "Egresos: Corrientes",
                      "Egresos: Remuneraciones",
                      "Egresos: Compras bienes y servicios",
                      "Egresos: Intereses", "Egresos: DGI",
                      "Egresos: BPS",
                      "Egresos: No corrientes",
                      "Egresos: Inversiones",
                      "Egresos: Dividendo",
                      "Resultado: Global"]},
    "ANCAP":
        {"Name": "ancap",
         "Colnames": ["Ingresos",
                      "Ingresos: Venta bienes y servicios",
                      "Ingresos: Otros",
                      "Ingresos: Transferencias GC", "Egresos",
                      "Egresos: Corrientes",
                      "Egresos: Remuneraciones",
                      "Egresos: Compras bienes y servicios",
                      "Egresos: Intereses", "Egresos: DGI",
                      "Egresos: BPS",
                      "Egresos: No corrientes",
                      "Egresos: Inversiones",
                      "Egresos: Var. stock petróleo",
                      "Egresos: Otros", "Egresos: Dividendo",
                      "Resultado: Global"]},
    "ANTEL":
        {"Name": "antel",
         "Colnames": ["Ingresos",
                      "Ingresos: Venta bienes y servicios",
                      "Ingresos: Otros",
                      "Ingresos: Transferencias GC", "Egresos",
                      "Egresos: Corrientes",
                      "Egresos: Remuneraciones",
                      "Egresos: Compras bienes y servicios",
                      "Egresos: Intereses", "Egresos: DGI",
                      "Egresos: BPS",
                      "Egresos: No corrientes",
                      "Egresos: Inversiones",
                      "Egresos: Dividendo", "Resultado: Global"]},
    "OSE":
        {"Name": "ose",
         "Colnames": ["Ingresos",
                      "Ingresos: Venta bienes y servicios",
                      "Ingresos: Otros",
                      "Ingresos: Transferencias GC", "Egresos",
                      "Egresos: Corrientes",
                      "Egresos: Remuneraciones",
                      "Egresos: Compras bienes y servicios",
                      "Egresos: Intereses", "Egresos: DGI",
                      "Egresos: BPS",
                      "Egresos: No corrientes",
                      "Egresos: Inversiones",
                      "Egresos: Dividendo",
                      "Resultado: Global"]},
    "UTE":
        {"Name": "ute",
         "Colnames": ["Ingresos",
                      "Ingresos: Venta bienes y servicios",
                      "Ingresos: Otros",
                      "Ingresos: Transferencias GC", "Egresos",
                      "Egresos: Corrientes",
                      "Egresos: Remuneraciones",
                      "Egresos: Compras bienes y servicios",
                      "Egresos: Intereses", "Egresos: DGI",
                      "Egresos: BPS",
                      "Egresos: No corrientes",
                      "Egresos: Inversiones",
                      "Egresos: Dividendo",
                      "Resultado: Global"]}
}

nat_accounts_metadata = {
    "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Cuentas%20Nacionales/cuadro_101t.xls":
        {"Rows": 12, "Inf. Adj.": "Const. 2005", "Unit": "Miles",
         "Seas": "NSA",
         "Name": "ind_con_nsa",
         "Colnames": ["PBI: Actividades primarias",
                      "PBI: Agricultura, ganadería, caza y silvucultura",
                      "PBI: Industrias manufactureras",
                      "PBI: Suministro de electricidad, gas y agua",
                      "PBI: Construcción",
                      "PBI: Comercio, reparaciones, restaurantes y hoteles",
                      "PBI: Transporte, almacenamiento y comunicaciones",
                      "PBI: Otras actividades",
                      "PBI: SIFMI", "PBI: Impuestos menos subvenciones",
                      "PBI"]},
    "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Cuentas%20Nacionales/cuadro_100t.xls":
        {"Rows": 12, "Inf. Adj.": "No", "Unit": "Miles", "Seas": "NSA",
         "Name": "ind_cur_nsa",
         "Colnames": ["PBI: Actividades primarias",
                      "PBI: Agricultura, ganadería, caza y silvucultura",
                      "PBI: Industrias manufactureras",
                      "PBI: Suministro de electricidad, gas y agua",
                      "PBI: Construcción",
                      "PBI: Comercio, reparaciones, restaurantes y hoteles",
                      "PBI: Transporte, almacenamiento y comunicaciones",
                      "PBI: Otras actividades",
                      "PBI: SIFMI", "PBI: Impuestos menos subvenciones",
                      "PBI"]},
    "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Cuentas%20Nacionales/cuadro_104t.xls":
        {"Rows": 10, "Inf. Adj.": "Const. 2005", "Unit": "Miles",
         "Seas": "NSA",
         "Name": "gas_con_nsa",
         "Colnames": ["PBI: Gasto total", "PBI: Gasto privado",
                      "PBI: Gasto público",
                      "PBI: Formación bruta de capital",
                      "PBI: Formación bruta de capital fijo",
                      "PBI: Formación bruta de capital fijo pública",
                      "PBI: Formación bruta de capital fijo privada",
                      "PBI: Exportaciones",
                      "PBI: Importaciones", "PBI"]},
    "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Cuentas%20Nacionales/cuadro_132t.xls":
        {"Rows": 12, "Inf. Adj.": "Const. 2005", "Unit": "2005=100",
         "Seas": "NSA", "Name": "ind_con_idx_nsa",
         "Colnames": ["PBI: Actividades primarias",
                      "PBI: Agricultura, ganadería, caza y silvucultura",
                      "PBI: Industrias manufactureras",
                      "PBI: Suministro de electricidad, gas y agua",
                      "PBI: Construcción",
                      "PBI: Comercio, reparaciones, restaurantes y hoteles",
                      "PBI: Transporte, almacenamiento y comunicaciones",
                      "PBI: Otras actividades",
                      "PBI: SIFMI", "PBI: Impuestos menos subvenciones",
                      "PBI"]},
    "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Cuentas%20Nacionales/cuadro_133t.xls":
        {"Rows": 12, "Inf. Adj.": "Const. 2005", "Unit": "2005=100",
         "Seas": "SA", "Name": "ind_con_idx_sa",
         "Colnames": ["PBI: Actividades primarias",
                      "PBI: Agricultura, ganadería, caza y silvucultura",
                      "PBI: Industrias manufactureras",
                      "PBI: Suministro de electricidad, gas y agua",
                      "PBI: Construcción",
                      "PBI: Comercio, reparaciones, restaurantes y hoteles",
                      "PBI: Transporte, almacenamiento y comunicaciones",
                      "PBI: Otras actividades",
                      "PBI: SIFMI", "PBI: Impuestos menos subvenciones",
                      "PBI"]},
    "https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Cuentas%20Nacionales/cuadro_130t.xls":
        {"Rows": 2, "Inf. Adj.": "No", "Unit": "Miles", "Seas": "NSA",
         "Name": "gdp_cur_nsa",
         "Colnames": ["PBI"]}}

reserves_cols = [
    'Saldo al inicio del período', '1. Compras netas de moneda extranjera',
    '1.1. Compras netas en el mercado',
    '1.2. Integración en dólares de valores del BCU',
    '1.3. Prefinanciación de exportaciones',
    '1.4. Cancelación de contratos forward', '1.5. Gobierno Central',
    '1.5.1. Utilizaciones de préstamos internacionales',
    '1.5.2. Otras compras netas al Gobierno Central',
    '1.6. Otros', '2. Depósitos del Sistema Bancario en el Banco Central',
    '2.1. Banca pública',
    '2.2. Banca privada', '3. Otros Depósitos en el Banco Central',
    '3.1. Depósitos de otras empresas de intermediación fin.',
    '3.2. Depósitos de casas de cambio y otras inst.',
    '3.3. Depósitos de empresas públicas y gob. dptales.',
    '4. Divisas de exportación a liquidar',
    '5. Obligaciones netas en ME con gob. central',
    '5.1. Colocación neta de bonos y letras', '5.1.1. Colocación bruta',
    '5.1.2. Amortizaciones',
    '5.1.3. Intereses y comisiones',
    '5.2. Otras obligaciones netas en ME',
    '5.2.1. Desembolsos de préstamos internacionales',
    '5.2.2. Servicio neto de préstamos internacionales',
    '5.3.3. Utilizaciones de préstamos internacionales',
    '5.4.5. Aporte de entes a cuenta de resultados',
    '5.4.6.  Compras de moneda extranjera',
    '5.4.7. Giros hacia y desde el BROU',
    '5.4.8. Integración en USD de títulos en UI y pesos-neto',
    '5.4.9. Otros', '6. Intereses netos',
    '6.1.Intereses pagados sobre depósitos del sist. fin.',
    '6.2. Intereses cobrados sobre fondos en el exterior',
    '6.3. Otros intereses y comisiones netos',
    '7. Otros', '7.1.  Préstamos y financiamientos EEPP',
    '7.2. Cuentas con organismos internacionales',
    '7.3. Fondos administrados', '7.4. Diferencias de arbitraje',
    '7.5. Diferencias de cotización e intereses devengados',
    '7.6. Depósitos especiales Clearstream Banking',
    '7.7. Solicitudes de giro al exterior en trámite', '7.8. Otros',
    'Variación total del período - 1+2+3+4+5+6+7',
    'Saldo al final del período'
]

fiscal_metadata = {
    "gps": {True: ["Ingresos: SPNF-SPC aj. FSS", "Egresos: Primarios SPNF-SPC",
                   "Egresos: Inversiones SPNF-SPC", "Intereses: SPC aj. FSS",
                   "Egresos: Totales SPC aj. FSS",
                   "Resultado: Primario intendencias",
                   "Resultado: Primario BSE", "Resultado: Primario BCU",
                   "Resultado: Primario SPC aj. FSS",
                   "Resultado: Global SPC aj. FSS"],
            False: ["Ingresos: SPNF-SPC", "Egresos: Primarios SPNF-SPC",
                    "Egresos: Inversiones SPNF-SPC",
                    "Intereses: SPC", "Egresos: Totales SPC",
                    "Resultado: Primario intendencias",
                    "Resultado: Primario BSE", "Resultado: Primario BCU",
                    "Resultado: Primario SPC",
                    "Resultado: Global SPC"]},
    "nfps": {
        True: ["Ingresos: SPNF-SPC aj. FSS", "Egresos: Primarios SPNF-SPC",
               "Egresos: Inversiones SPNF-SPC", "Intereses: SPNF aj. FSS",
               "Egresos: Totales SPNF aj. FSS",
               "Resultado: Primario intendencias",
               "Resultado: Primario BSE", "Resultado: Primario SPNF aj. FSS",
               "Resultado: Global SPNF aj. FSS"],
        False: ["Ingresos: SPNF-SPC", "Egresos: Primarios SPNF-SPC",
                "Egresos: Inversiones SPNF-SPC",
                "Intereses: SPNF", "Egresos: Totales SPNF",
                "Resultado: Primario intendencias",
                "Resultado: Primario BSE", "Resultado: Primario SPNF",
                "Resultado: Global SPNF"]},
    "gc": {True: ["Ingresos: GC-BPS aj. FSS", "Egresos: Primarios GC-BPS",
                  "Egresos: Inversiones GC-BPS",
                  "Intereses: GC-BPS aj. FSS",
                  "Egresos: Totales GC-BPS aj. FSS",
                  "Resultado: Primario GC-BPS aj. FSS",
                  "Resultado: Global GC-BPS aj. FSS"],
           False: ["Ingresos: GC-BPS", "Egresos: Primarios GC-BPS",
                   "Egresos: Inversiones GC-BPS",
                   "Intereses: GC-BPS", "Egresos: Totales GC-BPS",
                   "Resultado: Primario GC-BPS",
                   "Resultado: Global GC-BPS"]}
}
prod_details = [
    ['Pan y cereales', 'Carne', 'Pescado', 'Leche, queso y huevos',
     'Aceites y grasas', 'Frutas', 'Legumbres y Hortalizas',
     'Azúcar, mermelada, miel, chocolate y dulces de azúcar',
     'Productos alimenticios n.e.p.', 'Bebidas no alcohólicas',
     'Bebidas alcohólicas', 'Tabaco', 'PRENDAS DE VESTIR Y CALZADO',
     'Alquileres efectivos del alojamiento',
     'Conservación y reparación de la vivienda',
     'Suministro de agua y servicios diversos relacionados con la vivienda',
     'Electricidad', 'Gas', 'Combustibles sólidos',
     'Muebles y accesorios, alfombras y otros materiales para pisos',
     'Productos textiles para el hogar',
     'Artefactos para el hogar grandes, eléctricos o no',
     'Reparación de artefactos para el hogar',
     'Artículos de vidrio y cristal, vajilla y utensilios para el hogar',
     'Servicios domésticos y para el hogar',
     'Herramientas y equipo para el hogar y el jardín',
     'Bienes para el hogar no duraderos',
     'Productos, artefactos y equipo médicos',
     'Servicios para pacientes externos', 'Servicios de hospital',
     'Servicios médicos mutuales y colectivos', 'Adquisición de vehículos',
     'Funcionamiento de equipo de transporte personal',
     'Servicios de transporte', 'Servicios postales',
     'Equipo telefónico y de facsímile',
     'Servicios telefónicos y de facsímile',
     'Equipo audiovisual, fotográfico y de procesamiento de información',
     'Otros artículos y equipo para recreación, jardines y animales domésticos',
     'Servicios de recreación y culturales',
     'Periódicos, libros y papeles y útiles de oficina', 'Paquetes turísticos',
     'EDUCACIÓN', 'Servicios de alojamiento',
     'Servicios de suministro de comidas por contrato', 'Cuidado personal',
     'Efectos personales n.e.p.', 'Seguros', 'Otros servicios n.e.p.'],
    ['    Panes y cereales', '    Carnes y derivados', '    Otros alimentos',
     '    Lácteos y huevos', '    Aceites y grasas', '    Frutas',
     '    Verduras, legumbres y tubérculos',
     '    Azucar, cafe, te, yerba, cacao', '    Otros alimentos',
     '    Bebidas no alcohólicas', '    Bebidas alcohólicas', '  Tabaco',
     'Vestimenta Y Calzado', '    Alquileres brutos',
     '    Servicios y materiales p/reparación', '    Agua corriente',
     '    Electricidad', '    Gas', '    Combustible',
     '  Muebles, Acc. Fijos Y Reparaciones',
     '  Tejidos Para El Hogar Y Otros Acc.',
     '    Artefactos y electrodomésticos', '    Reparaciones del hogar',
     '    Cristalería, vajilla, utensillos ', '    Servicio doméstico',
     '  Servicios P/El Hogar Exc.Serv.Domestico',
     '    Artefactos y electrodomésticos',
     '  Productos Medicinales Y Farmaceuticos', '  Servicios Medicos',
     '  Servicios Medicos', '  Servicios Medicos',
     '  Equipo De Transporte Personal',
     '  Mantenimiento Y Utiliz. De Equipo Tpte.', '  Servicios De Transporte',
     '    Correo y encomiendas', '    Servicio telefónico',
     '    Servicio telefónico', '  Equipos Accesorios Y Reparaciones',
     '  Equipos Accesorios Y Reparaciones', '  Servicios De Esparcimiento',
     '  Libros, Periodicos Y Revistas', '    Gastos en excursiones',
     'Enseñanza', '    Servicio de hoteles y alojamiento',
     '    Comidas fuera del hogar', '  Cuidados Y Efectos Personales',
     '  Cuidados Y Efectos Personales', '    Servicios financieros',
     '    Otros servicios'],
    [1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
     1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
